# Generated by Django 5.0.2 on 2024-03-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('twitch_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('profile_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('embed_url', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='suggestions.twitchuser')),
            ],
        ),
    ]
