# Generated by Django 5.0.2 on 2024-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
