# Generated by Django 5.0.2 on 2024-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_suggestion_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='embed_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
